name: torchgeo-app
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.0
  - pytorch>=1.13.0
  - torchvision>=0.14.0
  - numpy>=1.20.0
  - pillow>=9.0.0
  - matplotlib>=3.5.0
  - pip:
    - streamlit>=1.22.0
    - torchgeo>=0.4.0
